spring:
  application:
    name: conversion-factor  h2:    console:      enabled: true  datasource:    url: jdbc:h2:mem:conversiondb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm  jpa:    show-sql: true
    
server:  port: 8001
  
  
  